### PR TITLE
[feat]: Handling for treasury BADGER bribing.

### PR DESCRIPTION
**Pull request by Tritium-VLK**
see:
https://github.com/Badger-Finance/Badger-Project-Planning/issues/75

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
Will bring to office hours.

**Comment by GalloDaSballo** [comment]
Missing Tests, do not PR Contract Changes without Tests

**Review by GalloDaSballo — CHANGES_REQUESTED** [review]
Missing tests, we cannot ever PR without Tests

**Comment by dapp-whisperer** [comment]
did this get any outstanding questions answered at office hours? I don’t recall.

I agree with alex - there should be a test to verify that the badger does indeed end up in the treasury in normal operation

**Comment by SHAKOTN** [comment]
This looks good to me, but I do agree that we can't review/merge without tests.
Related feature in autovoter: https://github.com/Badger-Finance/aura-autovoter/pull/70
Gonna be merged today

**Review by SHAKOTN — CHANGES_REQUESTED** [review]
Requesting tests

**Comment by GalloDaSballo** [comment]
Superseded by the work done here:
https://github.com/Badger-Finance/Badger-Project-Planning/issues/79

Closing

**Pull request closed without merging**
